name: Build and Push to Octopus Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ trigger-from-terraform ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore samples-simple-iis-website.sln

      - name: Set up Java (for OWASP scanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'HelloWorld-WebApp'
          scanpath: './'
          format: 'HTML'
          out: 'dependency-check-report'

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: dependency-check-report/dependency-check-report.html

      - name: Build solution
        run: msbuild samples-simple-iis-website.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Package build output
        run: |
          mkdir output
          $date = Get-Date -Format "yyyyMMdd"
          $version = "$date.${{ github.run_number }}"
          $zipName = "SimpleIISWebApp.$version.zip"
          powershell Compress-Archive -Path * -DestinationPath output\$zipName
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Push package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3
        with:
          api_key: API-DCNWIANX9TZEDGSQZ76VIICEWXJ2HM5
          server: https://sai.octopus.app
          packages: output/${{ env.ZIP_NAME }}
          space: Default

      - name: Create release in Octopus Deploy
        uses: OctopusDeploy/create-release-action@v3
        with:
          api_key: API-DCNWIANX9TZEDGSQZ76VIICEWXJ2HM5
          server: https://sai.octopus.app
          project: WebApps
          space: Default
          release_number: ${{ env.ZIP_NAME }}
          release_notes: "Release created from GitHub Actions on ${{ github.run_id }}"

      - name: Create deployment in Octopus Deploy
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          api_key: API-DCNWIANX9TZEDGSQZ76VIICEWXJ2HM5
          server: https://sai.octopus.app
          project: WebApps
          space: Default
          release_number: ${{ env.ZIP_NAME }}
          environments: Learn
