name: Build and Push to Octopus Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ trigger-from-terraform ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore samples-simple-iis-website.sln

      - name: Build solution
        run: msbuild samples-simple-iis-website.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Package build output
        run: |
          mkdir output
          $date = Get-Date -Format "yyyyMMdd"
          $version = "$date.${{ github.run_number }}"
          $zipName = "SimpleIISWebApp.$version.zip"
          powershell Compress-Archive -Path * -DestinationPath output\$zipName
          echo "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Push package to Octopus Deploy
        uses: OctopusDeploy/push-package-action@v3
        with:
          api_key: API-DCNWIANX9TZEDGSQZ76VIICEWXJ2HM5
          server: https://sai.octopus.app
          packages: output/${{ env.ZIP_NAME }}
          space: Default

      - name: Install Octopus CLI
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/OctopusDeploy/OctopusCLI/releases/latest/download/OctopusTools-windows-x64.zip" -OutFile "octo.zip"
          Expand-Archive .\octo.zip -DestinationPath .
          $env:Path += ";$PWD"
          Write-Output "Octopus CLI installed."

      - name: Create release in Octopus
        shell: pwsh
        run: |
          .\octo.exe create-release `
            --server "https://sai.octopus.app" `
            --apiKey "API-DCNWIANX9TZEDGSQZ76VIICEWXJ2HM5" `
            --project "WebApps" `
            --releaseNumber "${{ env.ZIP_NAME }}" `
            --packageVersion "${{ env.ZIP_NAME }}" `
            --deployTo "Development"
        env:
          OCTOPUS_CLI_AUTO_ACCEPT_PROMPTS: "true"

      - name: Deploy release to environment
        shell: pwsh
        run: |
          .\octo.exe deploy-release `
            --server "https://sai.octopus.app" `
            --apiKey "API-DCNWIANX9TZEDGSQZ76VIICEWXJ2HM5" `
            --project "WebApps" `
            --releaseNumber "${{ env.ZIP_NAME }}" `
            --deployTo "Learn" `
            --progress `
            --waitForDeployment